"""empty message

Revision ID: 388e2e096ec8
Revises: f58a810acd6f
Create Date: 2020-06-04 12:00:14.254131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388e2e096ec8'
down_revision = 'f58a810acd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'collections', ['name'])
    op.create_unique_constraint(None, 'collections', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='unique')
    # ### end Alembic commands ###
